### ISSUE TITLE
Python-LinkedIn - Project Available on PyPI

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [DEKHTIARJonathan/python3-linkedin#1]
Hello dear friends,

@ozgur @marshalllusher @abraham @ptwobrussell @SamuelMarks @EmlynC @ivankravets @devinbarry @joshowen @iacxc @yprez @jayzeng @Darune @adrian-sgn @johnfraney @lucavandro @mclate @scottydelta @mblakele @ismix @lyroge @marshyang @ikudriavtsev @kitsunde @ayyar @b3nelof0n

I would like to inform you that I have forked and mirrored the project *python-linkedin* which was originally created by @ozgur and converted to Python3 mainly by @marshalllusher.

I needed this library to work for a personal project and took the initiative to republish it to the PyPI Service : https://pypi.python.org/pypi/python3-linkedin

I hope you will appreciate this move, I have added quite some functionalities and tried to improve a little the documentation.

You all have been cited as contributors, and the contributions have been kept as yours during the mirroring process. I had to mirror and not fork due to the necessity of having "issues" enabled for the library.

Please feel free to comment if you disagree with anything I've done. I really intended to make it more easily accessible for anyone.

Have a great week,

Best Regards,

Jonathan DEKHTIAR

**Comment by marshallhumble** [comment]
Awesome! Thank you!

**Comment by jayzeng** [comment]
Glad to see this!
