### ISSUE TITLE
company search example returning no results

### ISSUE THREAD

**Issue by scheckley** [DEKHTIARJonathan/python3-linkedin#11]
`application.get_companies(company_ids=[1035], universal_names=['apple'], selectors=['name'], params={'is-company-admin': 'true'})`

returns:

`{'_total': 0}`

also, `https://developer.linkedin.com/documents/company-lookup-api-and-fields`  is a dead link.

Was this search revoked in the api recently? Usually I get access denied when something isn't available on the free api, but this returns no results which is strange.

**Comment by DEKHTIARJonathan** [comment]
I think this issue already have been discussed in #3. If you find your answers please close this issue.

Unfortunately, LinkedIn has a very poor documentation and it is fairly hard to keep up with the changes.

**Comment by scheckley** [comment]
ah thanks. yes, you are right and I will close this issue.
