### ISSUE TITLE
400 Client error : Bad Request

### ISSUE THREAD

**Issue by aurelg** [DEKHTIARJonathan/python3-linkedin#12]
Hi Jonathan,

As of today, I'm facing a problem when publishing links with the API using the `submit_share` function. Here is the error message (I edited it to remove my access token, which is valid: if I alter it, I get an `unauthorized` error) :

`
400 Client Error: Bad Request for url: https://api.linkedin.com/v1/people/~/shares?oauth2_access_token=XXXXXXXXXXXXXXXXXX: Invalid arguments: {S_400_BAD_REQUEST=Bad request}
`

Any idea about what's going on / how to debug it? :)

**Comment by aurelg** [comment]
It works now. Probably a problem w/LinkedIn.

**Comment by DEKHTIARJonathan** [comment]
My pleasure to help you as hard as possible ;)
