### ISSUE TITLE
redirect uri does not match

### ISSUE THREAD

**Issue by leeadh** [DEKHTIARJonathan/python3-linkedin#15]
Hello I was following this guide, ran the oauth2_authentication and got 

http://localhost:8000/?code=xxxxxx&state=yyyy

I then passed this token into oauth2_code2accesstoken under the authorization code. 

Howver, i got an error

`requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.linkedin.com/uas/oauth2/accessToken`

Whats wrong

**Comment by DEKHTIARJonathan** [comment]
What code are you using, can you post it here?

**Comment by DEKHTIARJonathan** [comment]
No answer, I'm closing
