### ISSUE TITLE
ImportError: cannot import name 'linkedin' from 'linkedin' 

### ISSUE THREAD

**Issue by lloydrayner** [DEKHTIARJonathan/python3-linkedin#17]
Hi, wondering if you can help with this issue?

I have installed the package and get the error when running 

from linkedin import linkedin

**Comment by DEKHTIARJonathan** [comment]
How do you want to be help you by giving virtually no information

**Comment by lloydrayner** [comment]
Hi, 

The error is I get is: 
`Traceback (most recent call last):
  File "<input>", line 1, in <module>
ImportError: cannot import name 'linkedin' from 'linkedin' (/Users/lrayner/PycharmProjects/LinkedIn2/venv/lib/python3.7/site-packages/linkedin.py)`

I get it on the first line 'from linkedin import linkedin'

Does this shed more light on it?

**Comment by DEKHTIARJonathan** [comment]
See issue #16. Not compatible with Python 3.7.
Feel free to contribute.
