### ISSUE TITLE
Where to get USER_TOKEN & USER_SECRET

### ISSUE THREAD

**Issue by AakashBasu** [DEKHTIARJonathan/python3-linkedin#21]
I am trying just to access my own LinkedIn profile data.

Steps followed:

- Setup a new application
- Get CLIENT_ID and CLIENT_SECRET

But, where to get the USER_TOKEN, USER_SECRET as mentioned here "You can simply use the 4 credentials that are provided to you in your LinkedIn application as part of an OAuth 1.0a flow and immediately access your data."? I've tried without it, and it doesn't work.

**Comment by AakashBasu** [comment]
@DEKHTIARJonathan Any help?

**Comment by estyxx** [comment]
Hi, 
For USER_TOKEN and USER_SECRET I just run this example: 
https://github.com/DEKHTIARJonathan/python3-linkedin/blob/master/examples/http_api.py

go in the browser  http://localhost:8080 and do the step of autentication it will appear a dictionary in the browser, there are you user_token and user_secret...

Bye :)
Ester
