### ISSUE TITLE
Authentication Problem when collecting token

### ISSUE THREAD

**Issue by Dnndmt** [DEKHTIARJonathan/python3-linkedin#7]
Hey guys,

I'm trying to connect to the basic profile api through jupyter. When I click on the link to get my token and authorize my application I get this error on the link:

http://localhost:8000/callback/?error=invalid_scope&error_description=Your+application+has+not+been+authorized+for+the+scope+%22r_fullprofile%22#!

I read that now you have to apply through email to get full profile access but for me only basic profile is enough as I don't have the time to wait for linked in to approve this. Is there a way to get around this problem? Maybe i can choose parameters for linkedin.PERMISSIONS.enums.values()? 

I'm a bit new to python and have to do this application for a school project. Some help would be greatly appreciate and thanks for making the updates for python 3!!

**Comment by DEKHTIARJonathan** [comment]
> Maybe i can choose parameters for linkedin.PERMISSIONS.enums.values()

You answered your own question, look what are the values returned by `linkedin.PERMISSIONS.enums.values()` and replaced this by the one you want.

You can also have a look to the examples in the repository
