### ISSUE TITLE
Examples of search: selectors?

### ISSUE THREAD

**Issue by arivero** [DEKHTIARJonathan/python3-linkedin#8]
Hello,

Any idea about if it is possible to narrow a company search, or generically a search, by some selector. I am thinking particularly in foundedYear. It is not a facet, and attempting just a 'keyword':'2015' does not seem to look into this field.

**Comment by DEKHTIARJonathan** [comment]
Try to do it with this tool: https://apigee.com/console/linkedin?apig_cc=1

If you manage to find a way to do what you think about, we could surely implement it in this library

**Comment by DEKHTIARJonathan** [comment]
Closing due to no response
