### ISSUE TITLE
Filters for People Search?

### ISSUE THREAD

**Issue by Frankjunyulin** [DEKHTIARJonathan/python3-linkedin#9]
Hi,
Can we use the filters like "location" while we are using search Api? Is there any example for that?
Also, I think the link "https://developer.linkedin.com/documents/people-search-api" that you provide doesn't work now.

**Comment by DEKHTIARJonathan** [comment]
LinkedIn APIs are not very well documented. Some are deprecated without notice.

If I have time I will try to fix it, if possible, else remove it
